### ISSUE TITLE
Crash with Gun Table

### ISSUE THREAD

**Issue by Kronon-Conspirator** [cybercat-mods/HWG#26]
when placing the gun table, if placed without back support/ a block behind it it will crash. tested with HWGMod-1.17-1.0.10
`---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 26/07/2021, 9:44 pm
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]} to down on Block{hwg:gun_table}, it is not an allowed value
	at net.minecraft.class_2688.method_11657(class_2688.java:125)
	at mod.azure.hwg.blocks.GunTableBlock.method_9605(GunTableBlock.java:105)
	at net.minecraft.class_1747.method_7707(class_1747.java:118)
	at net.minecraft.class_1747.redirect$eei000$hookPlace(class_1747.java:1529)
	at net.minecraft.class_1747.method_7712(class_1747.java:70)
	at net.minecraft.class_1747.method_7884(class_1747.java:49)
	at net.minecraft.class_1799.method_7981(class_1799.java:242)
	at net.minecraft.class_636.method_2896(class_636.java:339)
	at net.minecraft.class_310.method_1583(class_310.java:1646)
	at net.minecraft.class_310.method_1508(class_310.java:1900)
	at net.minecraft.class_310.method_1574(class_310.java:1728)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
`

**Comment by AzureDoom** [comment]
Yeah, it's already fixed locally, I just haven't been free to build it yet.
