### ISSUE TITLE
Crashed when tried using gun crafting table without the correct items on inventory

### ISSUE THREAD

**Issue by felipedeoliveirarios** [cybercat-mods/HWG#27]
I crafted a gun crafting table, opened it, clicked on a recipe, but only had a stick from the items needed, so the server crashed. This is the crash report:

```---- Minecraft Crash Report ----
// But it works on my machine.

Time: 8/7/21, 7:49 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_2653.<init>(int, int, int, net.minecraft.class_1799)'
	at mod.azure.hwg.client.gui.GunTableScreenHandler.updateResult(GunTableScreenHandler.java:73)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.lambda$onContentChanged$0(GunTableScreenHandler.java:79)
	at net.minecraft.class_3914.method_17394(class_3914.java:35)
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22)
	at net.minecraft.class_3914.method_17393(class_3914.java:34)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.method_7609(GunTableScreenHandler.java:78)
	at mod.azure.hwg.client.gui.GunTableInventory.method_5447(GunTableInventory.java:52)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.autofill(GunTableScreenHandler.java:183)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.switchTo(GunTableScreenHandler.java:163)
	at mod.azure.hwg.network.C2SMessageSelectCraft.handle(C2SMessageSelectCraft.java:27)
	at mod.azure.hwg.network.C2SMessageSelectCraft.lambda$receive$0(C2SMessageSelectCraft.java:34)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Linux (amd64) version 5.8.0-1035-gcp
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1349240048 bytes (1286 MiB) / 3221225472 bytes (3072 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 0
	Microarchitecture: Broadwell (Server)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 2
	Graphics card #0 name: Virtio SCSI
	Graphics card #0 vendor: Red Hat, Inc. (0x1af4)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x1004
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: RAM
	Virtual memory max (MB): 1967.44
	Virtual memory used (MB): 3874.19
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 6 total; -Xmx3G -Xms3G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 2.0.0+1.17
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.2.7
		alloy_forgery: Alloy Forgery 1.3.2
		amecsapi: Amecs API 1.1.5+mc21w16a
		apoli: Apoli 1.0.3
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.2.21
		artifice: Artifice 0.15.3+21w07a
		backslot: BackSlot 1.1.13
		caelus: Caelus API 0.0.16-1.17
		calio: Calio 1.0.1
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		carrier: Carrier 1.8.0
		cavebiomes: Cave Biomes 0.6.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.4
		croptopia: Croptopia 1.5.0
		dark-enchanting: Dark Enchanting 0.3.1-1.17
		de_javagl_obj: obj 0.3.0
		dual_riders: DualRiders 1.0.5
		elytratrinket: Elytra Trinket 2.0.1-1.17
		extraalchemy: Extra Alchemy 1.5.1
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fading: Fading 1.3.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fastdecay: FastDecay 1.0.0
		fiber: fiber 0.23.0-2
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		geckolib3: Geckolib 3.0.6
		givemehats: Give Me Hats! 1.6
		glassdoor: Glass Doors 1.5.0-1.16
		golemsgalore: Golems Galore 1.0.2+mc.1.17
		hwg: Happiness is a Warm Gun 1.0.6
		hydrogen: Hydrogen 0.3
		image2map: Image2Map 0.2.1
		inmis: Inmis 2.3.1-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		led: Light Emitting Diode 1.1.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.1.2-BETA+1.17
		lithium: Lithium 0.7.3
		magna: Magna 1.5.5-1.17-pre4
		maybe-data: Maybe data 1.0.1-1.17
		minecraft: Minecraft 1.17
		moborigins: Mob Origins 1.5.0
		mostructures: Mo' Structures 1.2.1-1.17
		myron: Myron 1.6.0
		nbtcrafting: NBT Crafting 2.0.19+mc1.17
		npcvariety: NPC Variety 2.1.0
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		owo: OwO 0.1
		patchouli: Patchouli 1.17-55-FABRIC-SNAPSHOT
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		respawnablepets: Respawnable Pets 1.17-2
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		rpgdifficulty: Rpg Difficulty 1.0.6
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		secretrooms: Secret Rooms 1.0.0+1.17
		simple_backpack: SimpleBackpack 1.1.13
		spiceoffabric: Spice of Fabric 1.3.4+1.17.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		strawdummy: Straw Dummy 1.5.0
		structurized: Structurized 1.3.0
		team_reborn_energy: Energy 0.1.1
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		trinkets: Trinkets 3.0.0
		truerooms: True Secret Rooms 1.1.4
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		untitledduckmod: Untitled Duck Mod 0.3.0
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		villagernames: Villager Names 2.0.0
		waystones: Waystones 2.0.2
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		wthit: wthit 3.6.1
		xaerominimap: Xaero's Minimap 21.12.2
		xaeroworldmap: Xaero's World Map 1.14.4
	Player Count: 2 / 10; [class_3222['Doigyfu'/149624, l='ServerLevel[world]', x=-114.14, y=64.00, z=75.34], class_3222['O_SiD'/160695, l='ServerLevel[world]', x=-116.25, y=65.00, z=76.71]]
	Data Packs: vanilla (incompatible), Fabric Mods, secretrooms:server_pack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by AzureDoom** [comment]
You are majorly outdated

**Comment by felipedeoliveirarios** [comment]
Updated the mod and geckolib. Tried it again and it's still crashing:
```---- Minecraft Crash Report ----
// My bad.

Time: 8/8/21, 3:59 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void net.minecraft.class_2653.<init>(int, int, int, net.minecraft.class_1799)'
	at mod.azure.hwg.client.gui.GunTableScreenHandler.updateResult(GunTableScreenHandler.java:73)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.lambda$onContentChanged$0(GunTableScreenHandler.java:79)
	at net.minecraft.class_3914.method_17394(class_3914.java:35)
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22)
	at net.minecraft.class_3914.method_17393(class_3914.java:34)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.method_7609(GunTableScreenHandler.java:78)
	at mod.azure.hwg.client.gui.GunTableInventory.method_5447(GunTableInventory.java:52)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.autofill(GunTableScreenHandler.java:183)
	at mod.azure.hwg.client.gui.GunTableScreenHandler.switchTo(GunTableScreenHandler.java:163)
	at mod.azure.hwg.network.C2SMessageSelectCraft.handle(C2SMessageSelectCraft.java:27)
	at mod.azure.hwg.network.C2SMessageSelectCraft.lambda$receive$0(C2SMessageSelectCraft.java:34)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:783)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:167)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:759)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:744)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:696)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17
	Minecraft Version ID: 1.17
	Operating System: Linux (amd64) version 5.8.0-1035-gcp
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1955457304 bytes (1864 MiB) / 3221225472 bytes (3072 MiB) up to 3221225472 bytes (3072 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 79 Stepping 0
	Microarchitecture: Broadwell (Server)
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 2
	Graphics card #0 name: Virtio SCSI
	Graphics card #0 vendor: Red Hat, Inc. (0x1af4)
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: 0x1004
	Graphics card #0 versionInfo: unknown
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 0.00
	Memory slot #0 type: RAM
	Virtual memory max (MB): 1967.44
	Virtual memory used (MB): 3489.28
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 6 total; -Xmx3G -Xms3G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		adorn: Adorn 2.0.0+1.17
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		adventurez: AdventureZ 1.2.7
		alloy_forgery: Alloy Forgery 1.3.2
		amecsapi: Amecs API 1.1.5+mc21w16a
		apoli: Apoli 1.0.3
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.2.21
		artifice: Artifice 0.15.3+21w07a
		backslot: BackSlot 1.1.13
		caelus: Caelus API 0.0.16-1.17
		calio: Calio 1.0.1
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		carrier: Carrier 1.8.0
		cavebiomes: Cave Biomes 0.6.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		conjuring: Conjuring 1.0.4
		croptopia: Croptopia 1.5.0
		dark-enchanting: Dark Enchanting 0.3.1-1.17
		de_javagl_obj: obj 0.3.0
		dual_riders: DualRiders 1.0.5
		elytratrinket: Elytra Trinket 2.0.1-1.17
		extraalchemy: Extra Alchemy 1.5.1
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.36.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b44633d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d03d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea83d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b44633d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa3d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b44633d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b44633d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da3103d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b44633d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b44633d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c03d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa3d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b44633d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b44633d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab61213d
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b44633d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b44633d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa3d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b44633d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa3d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab61213d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b44633d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b44633d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee3d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b44633d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab61213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b44633d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.11+e36969833d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b44633d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab61213d
		fabricloader: Fabric Loader 0.11.6
		fading: Fading 1.3.0
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingtree: FallingTree 2.12.1
		fastdecay: FastDecay 1.0.0
		fiber: fiber 0.23.0-2
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		geckolib3: Geckolib 3.0.11
		givemehats: Give Me Hats! 1.6
		glassdoor: Glass Doors 1.5.0-1.16
		golemsgalore: Golems Galore 1.0.2+mc.1.17
		hwg: Happiness is a Warm Gun 1.0.11
		hydrogen: Hydrogen 0.3
		image2map: Image2Map 0.2.1
		inmis: Inmis 2.3.1-1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		led: Light Emitting Diode 1.1.0
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.0.0+1.17
		libninepatch: LibNinePatch 1.1.0
		lifts: Lifts 1.1.2-BETA+1.17
		lithium: Lithium 0.7.3
		magna: Magna 1.5.5-1.17-pre4
		maybe-data: Maybe data 1.0.1-1.17
		minecraft: Minecraft 1.17
		moborigins: Mob Origins 1.5.0
		mostructures: Mo' Structures 1.2.1-1.17
		myron: Myron 1.6.0
		nbtcrafting: NBT Crafting 2.0.19+mc1.17
		npcvariety: NPC Variety 2.1.0
		omega-config: OmegaConfig 1.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.1
		owo: OwO 0.1
		patchouli: Patchouli 1.17-55-FABRIC-SNAPSHOT
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		playerabilitylib: Pal 1.3.0-nightly.1.17-rc1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		respawnablepets: Respawnable Pets 1.17-2
		roughlyenoughitems: Roughly Enough Items 6.0.264-alpha
		rpgdifficulty: Rpg Difficulty 1.0.6
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		secretrooms: Secret Rooms 1.0.0+1.17
		simple_backpack: SimpleBackpack 1.1.13
		spiceoffabric: Spice of Fabric 1.3.4+1.17.1
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		strawdummy: Straw Dummy 1.5.0
		structurized: Structurized 1.3.0
		team_reborn_energy: Energy 0.1.1
		terrarianslimes: Terrarian Slimes 1.1-BETA+1.17
		trinkets: Trinkets 3.0.0
		truerooms: True Secret Rooms 1.1.4
		tweed4_annotated: tweed4_annotated 1.0.0
		tweed4_base: tweed4_base 1.0.0
		tweed4_data: tweed4_data 1.0.0
		tweed4_data_hjson: tweed4_data_hjson 1.0.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.0
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.0
		untitledduckmod: Untitled Duck Mod 0.3.0
		vanilla-hammers: Vanilla Hammers 3.1.2-1.17
		villagernames: Villager Names 2.0.0
		waystones: Waystones 2.0.2
		wolveswitharmor: Wolves With Armor 1.6.0-1.17
		wthit: wthit 3.6.1
		xaerominimap: Xaero's Minimap 21.12.2
		xaeroworldmap: Xaero's World Map 1.14.4
	Player Count: 1 / 10; [class_3222['Doigyfu'/238, l='ServerLevel[world]', x=-114.14, y=64.00, z=75.34]]
	Data Packs: vanilla (incompatible), Fabric Mods, secretrooms:server_pack
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by AzureDoom** [comment]
Update your Fabric API

**Comment by felipedeoliveirarios** [comment]
So, i need to update the whole server?
EDIT: I mean, there is no newer version for fabric api for 1.17

**Comment by AzureDoom** [comment]
I would suggest as I built again 0.37.0, you are on 0.36.0. https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all?filter-game-version=1738749986%3a73242

**Comment by felipedeoliveirarios** [comment]
Yep. Starting from 0.36.1, Fabric api doesn't support 1.17 anymore, only 1.17.1. Looks like i need to upgrade everything.

**Comment by AzureDoom** [comment]
Yeah I only support latest

**Comment by felipedeoliveirarios** [comment]
Ok, ty.
