### ISSUE TITLE
JsonSyntaxException:  Parsing error loading recipe

### ISSUE THREAD

**Issue by Yucked** [cybercat-mods/HWG#47]
```java
[16:10:15] [Worker-Main-30/ERROR]: Parsing error loading recipe hwg:silvergun
com.google.gson.JsonSyntaxException: Unknown item 'hwg:silvergun'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[server-intermediary.jar:?]
        at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.read(GunTableRecipe.java:114) ~[HWGMod-1.18.1-1.0.2.jar:?]
        at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.method_8121(GunTableRecipe.java:100) ~[HWGMod-1.18.1-1.0.2.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[server-intermediary.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
[16:10:15] [Worker-Main-30/ERROR]: Parsing error loading recipe hwg:silverbullet
com.google.gson.JsonSyntaxException: Unknown item 'hwg:silver_bullet'
        at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
        at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[server-intermediary.jar:?]
        at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.read(GunTableRecipe.java:114) ~[HWGMod-1.18.1-1.0.2.jar:?]
        at mod.azure.hwg.util.recipes.GunTableRecipe$Serializer.method_8121(GunTableRecipe.java:100) ~[HWGMod-1.18.1-1.0.2.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:126) ~[server-intermediary.jar:?]
        at net.minecraft.class_1863.method_20705(class_1863.java:55) ~[server-intermediary.jar:?]
        at net.minecraft.class_1863.method_18788(class_1863.java:34) ~[server-intermediary.jar:?]
        at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_4014.method_18367(class_4014.java:70) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572) [?:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714) [?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
```

**Comment by AzureDoom** [comment]
Yes, these are items that only added when another mod is loaded, that mod hasn't been ready for me to add in support for. Ignore safely.

**Comment by Gavin-Heatherington** [comment]
What is the name of the mod that is needed?

**Comment by Gavin-Heatherington** [comment]
What is the name of the mod needed?

**Comment by gheatherington** [comment]
What is the name of the mod needed?

**Comment by AzureDoom** [comment]
Bewitchment but support hasn't been added back for 1.18.1 at this time so the log can be ignored.
