### ISSUE TITLE
Game crashes on startup.

### ISSUE THREAD

**Issue by caoqt1** [cybercat-mods/HWG#51]
I am on minecraft version 1.18.2, i installed the latest version of hwg and the latest version of geckolib for fabric and my game crashes after the launcher closes when pressing play

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hwg'!
Error Code: 255

[

**Comment by caoqt1** [comment]
Here is my whole crash log:




`---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 3/3/22, 10:50 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'hwg'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at mod.azure.hwg.HWGMod.onInitialize(HWGMod.java:77)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 20 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.13.0-30-generic
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 667628336 bytes (636 MiB) / 973078528 bytes (928 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM)2 Duo CPU     P7550  @ 2.26GHz
	Identifier: Intel64 Family 6 Model 23 Stepping 10
	Microarchitecture: Penryn (Client) / Penryn (Server)
	Frequency (GHz): 2.26
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: C79 [GeForce 9400]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x0861
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 5895.23
	Virtual memory used (MB): 2773.93
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1.01
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		fabric: Fabric API 0.47.9+1.18.2
		fabric-api-base: Fabric API Base 0.4.3+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.6+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.2+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.11+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.8+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.7+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.20+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.1+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.10+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.16+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.7+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.18+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.12+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.12+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.2+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.9+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.11+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.9+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.1+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.10+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.3+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.5+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.20+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.7+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.2+34b2a0ce60
		fabric-particles-v1: Fabric Particles (v1) 0.2.11+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.6+ca4be9c960
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.12+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.16+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.6+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.1+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.1+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.17+801ec85b60
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.9+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.13+d7c144a860
		fabric-textures-v0: Fabric Textures (v0) 1.0.11+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.13+cca23f9360
		fabricloader: Fabric Loader 0.13.3
		geckolib3: Geckolib 3.0.35
		hwg: Happiness is a Warm Gun 1.1.0
		iris: Iris 1.2.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.18.2
		org_anarres_jcpp: jcpp 1.4.14
		org_joml_joml: joml 1.10.2
		physicsmod: Physics Mod 2.6.7
		sodium: Sodium 0.4.1+build.15
		xaerominimap: Xaero's Minimap 22.3.0
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`

**Comment by AzureDoom** [comment]
Cloth config is clearly marked as a dependent. 1.18.1 works with 1.18.2
