### ISSUE TITLE
Incompatible "Polymer"

### ISSUE THREAD

**Issue by xMELOSx** [cybercat-mods/HWG#65]
Polymer 0.2.4 , 0.2.5
https://modrinth.com/mod/polymer

Drawing will stop when the gun is reloaded.

- Mods
fabric-api-0.57.0+1.19
geckolib-fabric-1.19-3.1.5
HWGMod-1.9-1.2.1
polymer-all-0.2.5+1.19
modmenu-4.0.0

`
[Netty Server IO #1/ERROR]: Encountered exception while handling in channel with name "hwg:sniper"
java.lang.IllegalArgumentException: Maybe a mod is trying to add entity in a non-server thread. This is probably not ImmPtl's issue
	at org.apache.commons.lang3.Validate.isTrue(Validate.java:159) ~[API%20geckolib-fabric-1.19-3.1.5.jar:?]
	at qouteall.imm_ptl.core.network.PacketRedirection.withForceRedirect(PacketRedirection.java:40) ~[imm_ptl_core-2.0.4-4c73880b5405fd1.jar:?]
	at net.minecraft.class_3244.localvar$bal000$polymer_sendRequiredPackets(class_3244.java:3844) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_14369(class_3244.java:1235) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_14364(class_3244.java:1221) ~[client-intermediary.jar:?]
	at qouteall.imm_ptl.core.network.PacketRedirection.sendRedirectedMessage(PacketRedirection.java:114) ~[imm_ptl_core-2.0.4-4c73880b5405fd1.jar:?]
	at net.minecraft.class_3324.md0e8174$lambda$broadcast$1$0(class_3324.java:3069) ~[client-intermediary.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at net.minecraft.class_3324.method_14605(class_3324.java:3067) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_8465(class_3218.java:903) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_43128(class_1937.java:404) ~[client-intermediary.jar:?]
	at mod.azure.hwg.item.weapons.SniperItem.reload(SniperItem.java:87) ~[HWGMod-1.9-1.2.1.jar:?]
	at mod.azure.hwg.network.PacketHandler.lambda$registerMessages$10(PacketHandler.java:100) ~[HWGMod-1.9-1.2.1.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:89) ~[fabric-networking-api-v1-1.0.27+7fe97409a9-b450bc767592f9dd.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.receive(ServerPlayNetworkAddon.java:38) ~[fabric-networking-api-v1-1.0.27+7fe97409a9-b450bc767592f9dd.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [fabric-networking-api-v1-1.0.27+7fe97409a9-b450bc767592f9dd.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [fabric-networking-api-v1-1.0.27+7fe97409a9-b450bc767592f9dd.jar:?]
	at net.minecraft.class_3244.handler$zel000$handleCustomPayloadReceivedAsync(class_3244.java:2383) [client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12075(class_3244.java) [client-intermediary.jar:?]
	at net.minecraft.class_2817.method_12199(class_2817.java:38) [client-intermediary.jar:?]
	at net.minecraft.class_2817.method_11054(class_2817.java:7) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:171) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:156) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:54) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Comment by AzureDoom** [comment]
Yeah, that mod is messaging with packets, nothing we can do.
